auto: true
blah: Hello

brigade:
    name: Luna Ilena 
    city: Grand Haven
    github: "https://github.com/lunailena"
    mailchimp: "http://eepurl.com/ouJJf"
    facebook: "https://www.facebook.com/lunailena"

content:
    title: Luna Ilena | A landscaping company that puts you first.
    contact: "Donna is looking forward to hearing from you, email her at: (<a href=\"mailto:lunailena@lunailena.com\">lunailena@lunailena.com</a>."
    banner: ./images/Banner.jpg
    banner-large: "/images/Banner-500-progressive.jpg"
    banner-small: "/images/Banner-300-progressive.jpg"
    projects:
      - name: Landscaping 
        content: "Luna Ilena is a premier landscape design firm, we strive to make the perfect design that is both maintanable and suitable for your specific needs."

      - name: Maintenence
        content: "We can provide full service maintenence of your garden beds and make sure your landscaping looks great every season."

      - name: Custom Design
        content: "Have an Idea? Let us help you make your idea a reality."

google-analytics:
    use: false
    code: 9999999
